# Human Sound Dataset

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
import tensorflow as tf

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\fram

In [2]:
df = pd.read_csv('voice.csv')

In [3]:
df.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

In [4]:
df['label'].value_counts()

female    1584
male      1584
Name: label, dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['label'] = le.fit_transform(df['label'])

In [6]:
df.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000      1  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632      1  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512      1  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119      1  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274      1  

[5 rows x 21 columns]

In [7]:
df['label'].value_counts() 
# Male is 1
# Female is 0

1    1584
0    1584
Name: label, dtype: int64

In [13]:
# Training the data into X and y
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [14]:
print(X)
print(y)

[[0.05978098 0.06424127 0.03202691 ... 0.0078125  0.         0.        ]
 [0.06600874 0.06731003 0.04022873 ... 0.0546875  0.046875   0.05263158]
 [0.0773155  0.08382942 0.03671846 ... 0.015625   0.0078125  0.04651163]
 ...
 [0.14205626 0.09579843 0.18373124 ... 2.9375     2.9296875  0.19475862]
 [0.14365874 0.09062826 0.18497617 ... 3.59375    3.5859375  0.31100218]
 [0.16550895 0.09288354 0.18304392 ... 0.5546875  0.546875   0.35      ]]
[1 1 1 ... 0 0 0]


In [15]:
# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [16]:
# Feature scaling the entire data
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.fit_transform(X_test)

In [54]:
# Building our Logisitic Regression Model
logmodel = LogisticRegression()
logmodel.fit(X_train, y_train)

predictions = logmodel.predict(X_test)

acc_log = accuracy_score(y_test, predictions)*100
acc_log

97.79179810725552

In [55]:
# Building our Random Forest Model
randmod = RandomForestClassifier(n_estimators = 100)
randmod.fit(X_train, y_train)

predictions_r = randmod.predict(X_test)

acc_rand = accuracy_score(y_test, predictions_r)*100
acc_rand

98.42271293375394

In [30]:
# Building our ANN Model
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [31]:
# Training our ANN model
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 2534 samples
Epoch 1/100
2534/2534 [==============================] - 1s 529us/sample - loss: 0.5457 - accuracy: 0.7463
Epoch 2/100
2534/2534 [==============================] - 0s 99us/sample - loss: 0.4263 - accuracy: 0.8706
Epoch 3/100
2534/2534 [==============================] - 0s 81us/sample - loss: 0.3355 - accuracy: 0.8950
Epoch 4/100
2534/2534 [==============================] - 0s 95us/sample - loss: 0.2666 - accuracy: 0.9021
Epoch 5/100
2534/2534 [==============================] - 0s 81us/sample - loss: 0.2027 - accuracy: 0.9373
Epoch 6/100
2534/2534 [==============================] - 0s 85us/sample - loss: 0.1530 - accuracy: 0.9597
Epoch 7/100
2534/2534 [==============================] - 0s 105us/sample - loss: 0.1198 - accuracy: 0.9676
Epoch 8/100
2534/2534 [==============================] - 0s 85us/sample - loss: 0.0995 - accuracy: 0.9712
Epoch 9/100
2534/2534 [===========

2534/2534 [==============================] - 0s 73us/sample - loss: 0.0414 - accuracy: 0.9830
Epoch 75/100
2534/2534 [==============================] - 0s 73us/sample - loss: 0.0413 - accuracy: 0.9842
Epoch 76/100
2534/2534 [==============================] - 0s 110us/sample - loss: 0.0407 - accuracy: 0.9850
Epoch 77/100
2534/2534 [==============================] - 0s 71us/sample - loss: 0.0420 - accuracy: 0.9838
Epoch 78/100
2534/2534 [==============================] - 0s 95us/sample - loss: 0.0411 - accuracy: 0.9834
Epoch 79/100
2534/2534 [==============================] - 0s 87us/sample - loss: 0.0405 - accuracy: 0.9834
Epoch 80/100
2534/2534 [==============================] - 0s 84us/sample - loss: 0.0406 - accuracy: 0.9834
Epoch 81/100
2534/2534 [==============================] - 0s 107us/sample - loss: 0.0407 - accuracy: 0.9838
Epoch 82/100
2534/2534 [==============================] - 0s 83us/sample - loss: 0.0403 - accuracy: 0.9842s - loss: 0.0411 - accuracy: 
Epoch 83/100
2534/2

In [79]:
print(np.concatenate((predictions_ann.reshape(len(predictions_ann), 1), y_test.reshape(len(y_test), 1)), 1))

[[1.24514103e-04 0.00000000e+00]
 [9.99922097e-01 1.00000000e+00]
 [2.68220901e-07 0.00000000e+00]
 ...
 [9.89629328e-01 1.00000000e+00]
 [5.71933469e-06 0.00000000e+00]
 [5.73548116e-03 0.00000000e+00]]


In [85]:
predictions_ann = ann.predict(X_test)
predictions_ann

array([[1.24514103e-04],
       [9.99922097e-01],
       [2.68220901e-07],
       [1.60932541e-06],
       [9.98238564e-01],
       [9.99989092e-01],
       [3.51756811e-04],
       [4.97102737e-05],
       [9.99986887e-01],
       [0.00000000e+00],
       [9.99958992e-01],
       [2.07734108e-03],
       [5.08978963e-03],
       [9.99967098e-01],
       [1.55896604e-01],
       [2.17795372e-04],
       [2.79518664e-02],
       [9.99817133e-01],
       [9.88281369e-01],
       [5.96046448e-08],
       [4.76837158e-07],
       [9.99996722e-01],
       [9.99998808e-01],
       [8.03917646e-04],
       [2.35438347e-06],
       [9.89634156e-01],
       [1.22854114e-03],
       [1.25169754e-06],
       [4.90248203e-05],
       [9.99995232e-01],
       [4.82344627e-03],
       [1.12950802e-05],
       [9.99823868e-01],
       [8.90496612e-01],
       [9.99599457e-01],
       [1.19209290e-07],
       [9.99999881e-01],
       [4.91085649e-03],
       [9.99943495e-01],
       [9.99977827e-01],


In [68]:
results = pd.DataFrame(data = [acc_log, acc_rand, acc_ann], index = ['Logistic Regression',
                                                                    'Random Forest Classifier', 'Artificial Neural Network'],
                      columns = ['Score'])
results

In [69]:
results

Score
Logistic Regression        97.791798
Random Forest Classifier   98.422713
Artificial Neural Network  97.791798

In [82]:
from sklearn.metrics import classification_report, confusion_matrix

In [84]:
print(classification_report(y_test, predictions_r))
print(confusion_matrix(y_test, predictions_r))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       301
           1       0.99      0.98      0.98       333

    accuracy                           0.98       634
   macro avg       0.98      0.98      0.98       634
weighted avg       0.98      0.98      0.98       634

[[297   4]
 [  6 327]]


In [90]:
df.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000      1  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632      1  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512      1  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119      1  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274      1  

[5 rows x 21 columns]